name: Demo CI/CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  demo-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Simulasi Install Dependency
        run: echo "Sedang menginstall library yang dibutuhkan..."

      - name: Membuat surat
        shell: cmd
        run: |
          echo Halo! Aku Liz dari Lumiere. > surat_dari_liz.txt
          echo Aku bikin surat ini otomatis lho, Dibikinnya pas tanggal %DATE% jam %TIME% >> surat_dari_liz.txt

      - name: Selesai
        run: echo "Deployment Berhasil!"
